update-base-environment: make action self-contained

diff --git a/.github/actions/update-base-environment/action.yaml b/.github/actions/update-base-environment/action.yaml
--- a/.github/actions/update-base-environment/action.yaml
+++ b/.github/actions/update-base-environment/action.yaml
@@ -74,7 +74,26 @@ runs:
 
     - name: Resolve version
       if: inputs.image-version == ''
-      uses: Energinet-DataHub/.github/.github/actions/docker-image-version
+      shell: bash
+      run: |
+        if [ "${{ github.event_name }}" = 'push' ] && [ "${{ github.ref_name }}" = 'main' ]; then
+          version="$(git rev-parse --short ${{ github.sha }})"
+        elif [ "${{ github.event_name }}" = 'pull_request' ]; then
+          version="${{ github.sha }}-pr.${{ github.event.pull_request.number }}"
+        elif [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ ${{ inputs.allow-dispatch }} ]; then
+          if [ "${{ github.ref_name }}" = 'main' ]; then
+            version="$(git rev-parse --short ${{ github.sha }})"
+          else
+            sanitized_branch=$(printf '${{ github.ref_name }}' | sed 's/[^a-zA-Z0-9]//g')
+            version="${{ github.sha }}.${sanitized_branch}"
+          fi
+        else
+          >&2 echo "::error:: Unsupported invocation: ${{ github.event_name }}"
+          exit 1
+        fi
+        echo "version=${version}" >> $GITHUB_OUTPUT
+        echo "version=${version}" >> $GITHUB_ENV
+        echo "version: $version"
 
     - name: Override version
       if: inputs.image-version != ''
