Update dotnet-build-prerelease.yml

diff --git a/.github/workflows/dotnet-build-prerelease.yml b/.github/workflows/dotnet-build-prerelease.yml
--- a/.github/workflows/dotnet-build-prerelease.yml
+++ b/.github/workflows/dotnet-build-prerelease.yml
@@ -94,8 +94,8 @@ jobs:
           forbidden_version=$(jq -r '.. | objects | select(.id == "FluentAssertions" and .resolvedVersion >= "8.0.0") | .resolvedVersion' versions.json)
 
           if [ -n "$forbidden_version" ]; then
-          echo -e "::error title='Forbidden FluentAssertions version detected'::Forbidden 'FluentAssertions' version $forbidden_version found"
-          exit 1
+            echo -e "::error title='Forbidden FluentAssertions version detected'::Forbidden 'FluentAssertions' version $forbidden_version found"
+            exit 1
           fi
 
       - name: Build solution
